# Generated by Django 5.0.7 on 2024-08-06 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_rename_nomedatanascimento_pessoa_datanascimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='idPessoa',
            new_name='idpessoa',
        ),
    ]
