# Generated by Django 5.0.7 on 2024-08-06 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_rename_idpessoa_pessoa_idpessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='datanascimento',
            new_name='data_nascimento',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='nomemae',
            new_name='nome_mae',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='nomepai',
            new_name='nome_pai',
        ),
    ]
