# Generated by Django 5.0.7 on 2024-08-06 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_rename_datanascimento_pessoa_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='data_nascimento',
            new_name='date_born',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='nome_mae',
            new_name='name_father',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='nome_pai',
            new_name='name_mother',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='idpessoa',
            new_name='pessoa_id',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='salario',
            new_name='salary',
        ),
    ]
