# Generated by Django 5.0.7 on 2024-08-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('idPessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('nomePai', models.CharField(max_length=60)),
                ('nomeMae', models.CharField(max_length=60)),
                ('nomeDataNascimento', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpf', models.CharField(max_length=14, unique=True)),
            ],
        ),
    ]
