# Generated by Django 5.0.7 on 2024-08-06 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='nomeDataNascimento',
            new_name='datanascimento',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='nomeMae',
            new_name='nomemae',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='nomePai',
            new_name='nomepai',
        ),
    ]
